### ISSUE TITLE
la clave de admin passwd of admin

### ISSUE THREAD

**Issue by discapacidad5** [networksoft/erp.multinivel#1]
hola estoy empezando a estudiar programacion y me gusto tu proyecto pero que está bien ordenado pero tengo ya dos dias matandome la cabeza para hacerlo funcionar pero no tengo la base de dato  me podrian facilitar la base de datos quiero trabajar en un módulo que permita hacer multinivel pero para bancos en ves de venta serian créditos y se repartieron los intereses en una red multinivel

**Comment by qcmarcel** [comment]
ok, disculpa la tardanza, es que el anterior lider no manejaba bn esta herramienta. Te voy a pasar un branch con ese informacion para que puedas trabajar en ello.
